### ISSUE TITLE
Chinese output garbled 

### ISSUE THREAD

**Issue by chenxiaoliang0901** [HiromuHota/webspoon-docker#39]
hello  The input data contains Chinese, but the Chinese data is disorderly when output，can you helo me

**Comment by HiromuHota** [comment]
Can you upload a screenshot?

**Comment by chenxiaoliang0901** [comment]
![image](https://user-images.githubusercontent.com/32791398/81249007-38073000-9050-11ea-82dc-4f60ff6d235d.png)
![image](https://user-images.githubusercontent.com/32791398/81249018-3c334d80-9050-11ea-8b8e-32d0219d5b54.png)
![image](https://user-images.githubusercontent.com/32791398/81249031-405f6b00-9050-11ea-8e6a-06752d65db01.png)

it is hive to hive

**Comment by HiromuHota** [comment]
Thank you for the screenshot.
I think this happens also on Spoon because webSpoon and Spoon use pretty much the same execution engine. Please check it if you can.
If this happens also on Spoon, I think you can find a solution at the old [Pentaho Forums](https://forums.pentaho.com/) or the [new one](https://community.hitachivantara.com/s/pentaho).

**Comment by HiromuHota** [comment]
Also, I think this is not an issue but an encoding (or field type?) is not properly set.

**Comment by chenxiaoliang0901** [comment]
Thank you.
How to build a cluster
