### ISSUE TITLE
Could you provide steps to upgrade docker content?

### ISSUE THREAD

**Issue by gurumark** [HiromuHota/webspoon-docker#6]
Could you provide steps as part of the documentation on how to upgrade the pdi to the lastest version since it will be the case in the future.
Thanks.

**Comment by HiromuHota** [comment]
You will not upgrade the pdi inside of the Docker container.
This is against the best practices of Docker (i.e., immutable infrastructure).
See [here](https://www.slideshare.net/jpetazzo/immutable-infrastructure-with-docker-and-containers-gluecon-2015) for example for more details.

Instead, you will deploy another Docker container using a new Docker image.
To keep your Kettle files, you have to do volume mounting from host to container as below so that the contents of `.kettle` and `.pentaho` will be stored on the host machine (hence not lost when re-deploying a Docker container).
```
$ docker run -d -p 8080:8080 -v kettle:/root/.kettle -v pentaho:/root/.pentaho hiromuhota/webspoon:latest-full
```

**Comment by HiromuHota** [comment]
Close assuming it's been solved.
